"""The server half of the caproto stub. See the package docstring."""

from typing import Any

class PVGroup:
    def __init__(self, prefix: str, **keywords: Any) -> None: ...
    @property
    def pvdb(self) -> dict[str, Any]: ...

def pvproperty(*arguments: Any, **keywords: Any) -> Any: ...
def run(pvdb: dict[str, Any], **keywords: Any) -> None: ...
